name: Test Snap Package

on:
  push:
    paths:
      - 'internal/utils/macos.go'
      - '.github/workflows/test-snap.yml'
  pull_request:
    paths:
      - 'internal/utils/macos.go'
      - '.github/workflows/test-snap.yml'
  workflow_dispatch:

jobs:
  test-snap:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install ipsw via snap
      run: |
        sudo snap install ipsw
        
    - name: Test ipsw basic functionality
      run: |
        ipsw version
        
    - name: Test apfs-fuse detection (expected to fail initially)
      continue-on-error: true
      run: |
        echo "Testing apfs-fuse detection without apfs-fuse installed..."
        # This should fail gracefully and suggest installing apfs-fuse
        ipsw extract --dyld --remote https://updates.cdn-apple.com/2023FallFCS/fullrestores/042-41883/7AF02F3A-B388-4A39-A966-EF4C5BE76E02/iPhone15,2_17.0_21A329_Restore.ipsw --output /tmp/test-extract || true
        
    - name: Install dependencies for apfs-fuse
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse3-dev build-essential cmake git libbz2-dev

    - name: Build and install apfs-fuse
      run: |
        git clone --recursive https://github.com/sgan81/apfs-fuse.git /tmp/apfs-fuse
        cd /tmp/apfs-fuse
        # Initialize submodules (needed for lzfse dependency)
        git submodule update --init --recursive
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
        sudo make install
        sudo ldconfig  # Update library cache
        
    - name: Verify apfs-fuse installation
      run: |
        which apfs-fuse || echo "apfs-fuse not in PATH"
        ls -la /usr/local/bin/apfs-fuse || echo "apfs-fuse not in /usr/local/bin"
        
    - name: Test with IPSW_APFS_FUSE_PATH environment variable
      continue-on-error: true
      run: |
        export IPSW_APFS_FUSE_PATH=/usr/local/bin/apfs-fuse
        echo "Testing with IPSW_APFS_FUSE_PATH=$IPSW_APFS_FUSE_PATH"
        # This should work if our fix is correct
        ipsw extract --dyld --remote https://updates.cdn-apple.com/2023FallFCS/fullrestores/042-41883/7AF02F3A-B388-4A39-A966-EF4C5BE76E02/iPhone15,2_17.0_21A329_Restore.ipsw --output /tmp/test-extract-with-env || true
        
    - name: Test snap confinement behavior
      run: |
        echo "=== Snap info ==="
        snap list ipsw
        echo "=== Snap connections ==="
        snap connections ipsw
        echo "=== PATH from snap environment ==="
        snap run ipsw --help | head -5 || true
        echo "=== Testing PATH visibility ==="
        echo $PATH
        echo "=== Available interfaces for ipsw snap ==="
        snap interface | grep -E "(system-files|removable-media|home)" || echo "No relevant interfaces found"
        
    - name: Test alternative apfs-fuse locations for snap users
      continue-on-error: true
      run: |
        echo "=== Testing various apfs-fuse installation methods for snap users ==="
        
        # Method 1: System-wide installation (what we just did)
        echo "Method 1: System installation (/usr/local/bin)"
        ls -la /usr/local/bin/apfs-fuse || echo "Not found in /usr/local/bin"
        
        # Method 2: Try to install in user space
        echo "Method 2: User space installation"
        mkdir -p $HOME/.local/bin
        if [ -f /usr/local/bin/apfs-fuse ]; then
          cp /usr/local/bin/apfs-fuse $HOME/.local/bin/
          echo "Copied to $HOME/.local/bin/apfs-fuse"
        fi
        
        # Method 3: Test with IPSW_APFS_FUSE_PATH from different locations
        echo "Method 3: Testing environment variable with different paths"
        for path in "/usr/local/bin/apfs-fuse" "$HOME/.local/bin/apfs-fuse" "/usr/bin/apfs-fuse"; do
          if [ -f "$path" ]; then
            echo "Found apfs-fuse at: $path"
            export IPSW_APFS_FUSE_PATH="$path"
            echo "Testing with IPSW_APFS_FUSE_PATH=$path"
            # Quick test to see if our enhanced detection works
            timeout 30s ipsw extract --dyld --remote https://updates.cdn-apple.com/2023FallFCS/fullrestores/042-41883/7AF02F3A-B388-4A39-A966-EF4C5BE76E02/iPhone15,2_17.0_21A329_Restore.ipsw --output /tmp/test-extract-method3 || echo "Test with $path failed or timed out"
            break
          fi
        done
        
    - name: Document findings
      run: |
        echo "=== Test Results Summary ==="
        echo "This workflow tests ipsw snap package functionality and apfs-fuse detection."
        echo "Key findings will be logged above for debugging snap confinement issues."
        echo "Check the step results to see if our enhanced apfs-fuse detection works."