name: Update Entitlements DB

on:
  schedule:
    - cron: '0 19 * * *'  # daily at 11:00 PST (19:00 UTC)
  workflow_dispatch:

jobs:
  update-entitlements-db:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build ipsw CLI
        run: |
          go build -o ipsw ./cmd/ipsw

      - name: Determine latest IPSW URL
        id: get-ipsw
        run: |
          # TODO: replace with actual logic to fetch the latest IPSW URL
          echo "CURRENT_IPSW_URL=$(./ipsw dl ipsw --device iPhone17,1 --latest --urls)" >> $GITHUB_ENV

      - name: Check for new IPSW
        id: check-ipsw
        run: |
          LAST=$(jq -r '.latest_ipsw.url // ""' hack/.watch_cache)
          echo "Last cached IPSW URL: $LAST"
          echo "Current IPSW URL: $CURRENT_IPSW_URL"
          if [ "$LAST" = "$CURRENT_IPSW_URL" ]; then
            echo "No new IPSW found; skipping"
            echo "should_update=false" >> $GITHUB_OUTPUT
          else
            echo "New IPSW found; proceeding with update"
            echo "should_update=true" >> $GITHUB_OUTPUT
          fi

      - name: Download IPSW
        if: steps.check-ipsw.outputs.should_update == 'true'
        run: |
          curl -L "$CURRENT_IPSW_URL" -o latest.ipsw

      - name: Generate entitlements database
        if: steps.check-ipsw.outputs.should_update == 'true'
        run: |
          ./ipsw ent --db www/static/db/ipsw.db --ipsw latest.ipsw

      - name: Commit and push updated DB
        if: steps.check-ipsw.outputs.should_update == 'true'
        run: |
          jq --arg url "$CURRENT_IPSW_URL" '.latest_ipsw = {"url": $url}' hack/.watch_cache > hack/.watch_cache.tmp
          mv hack/.watch_cache.tmp hack/.watch_cache
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add hack/.watch_cache www/static/db/ipsw.db
          git commit -m "chore(ents): update to $CURRENT_IPSW_URL [skip ci]" || echo "No changes to commit"
          git push 